language: scala

sudo: true

jdk: oraclejdk8

scala:
   - 2.12.4

services:
  - docker

before_install:
  - docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=127.0.0.1 --env ADVERTISED_PORT=9092 spotify/kafka
  - docker run -d -p 27018:27018  mongo:3.4.3 mongod --port 27018
  - docker run -d -p 8000:8000 --env SCALITY_ACCESS_KEY_ID=newAccessKey --env SCALITY_SECRET_ACCESS_KEY=newSecretKey scality/s3server