version: '3'
services:

  mongo:
    image: mongo:3.4.3
    ports:
      - 27017:27017
    networks:
      - nio-net

  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.1
    ports:
      - 32182:32181
    networks:
      - nio-net
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:3.2.1
    ports:
      - 29092:29092
    networks:
      - nio-net
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true

  s3server:
    image: scality/s3server
    ports:
      - 8000:8000
    networks:
      - nio-net
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey

  nio:
    image: maif/nio
    ports:
      - 9000:9000
    networks:
      - nio-net
    expose:
      - 9000
    environment:
      - KAFKA_HOST=kafka:29092
      - CELLAR_ADDON_HOST=http://s3server:8000
      - MONGODB_ADDON_URI=mongodb://mongo:27017/nio
    depends_on:
      - mongo
      - kafka
      - s3server
      - otoroshi

  otoroshi:
    image: maif/otoroshi:1.2.0
    networks:
      - nio-net
    environment:
      - APP_STORAGE=redis
      - REDIS_HOST=redis
      - PORT=8080
      - APP_IMPORT_FROM=./config/otoroshi-state.json
      - APP_DOMAIN=foo.bar
    volumes:
      - "./config"
    expose:
      - 8080
    depends_on:
      - redis

  redis:
    image: redis:4.0.8
    expose:
      - 6379
    networks:
      - nio-net
    command: redis-server --appendonly yes
    volumes:
      - ./data/otoroshi-data

  nginx-otoroshi:
    image: nginx
    expose:
      - 8080
    ports:
      - 8889:8080
    networks:
      - nio-net
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otoroshi

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      - SERVER_NAME=kibana.foo.bar
      - ELASTICSEARCH_URL=http://elastic:9200
    expose:
      - 5601
    networks:
      - nio-net
    depends_on:
      - elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es-data
    expose:
      - 9200
    networks:
      - nio-net

networks:
  nio-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.10/24
