version: '3'
services:
  mongo:
    image: mongo:3.4.3
    ports:
      - 27017:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.3
    ports:
      - 32182:32181
    expose:
      - 32181
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:5.2.3
    ports:
      - 29092:29092
    expose:
      - 29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true

  s3server:
    image: scality/s3server
    expose:
      - 8000
    environment:
      - SCALITY_ACCESS_KEY_ID=newAccessKey
      - SCALITY_SECRET_ACCESS_KEY=newSecretKey
      - LOG_LEVEL=trace
      - ENDPOINT=s3server

  nio:
    image: maif/nio
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      - KAFKA_HOST=kafka:29092
      - CELLAR_ADDON_HOST=http://s3server:8000
      - MONGODB_ADDON_URI=mongodb://mongo:27017/nio
      - DB_FLUSH=true
      - SECURITY_MODE=default
    depends_on:
    - mongo
    - kafka
    - s3server